import { Geist, Geist_Mono } from "next/font/google";
import { getServerSession } from "next-auth/next";
import ClientSessionProvider from "@/lib/ClientSessionProvider";
import { Toaster } from 'react-hot-toast';

import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import './globals.css';
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientSessionProvider session={session}>
          {children}
          <Toaster position="top-right" />
        </ClientSessionProvider>
      </body>
    </html>
  );
}